const REQUEST_TRANSLINK_BUS_STOPS = 'REQUEST_TRANSLINK_BUS_STOPS';
const RECEIVE_TRANSLINK_BUS_STOPS = 'RECEIVE_TRANSLINK_BUS_STOPS';
const UPDATE_VIEW_PORT = 'UPDATE_VIEW_PORT';

export default {
  UPDATE_VIEW_PORT,
  REQUEST_TRANSLINK_BUS_STOPS,
  RECEIVE_TRANSLINK_BUS_STOPS
};
